openapi: 3.0.1

info:
  title: Simplgrocr API
  description: Simplgrocr API
  version: 1.0.0

paths:
  /api/v1/market:
    post:
      tags:
        - market
      summary: Create a new market
      description: Create a new market
      operationId: createMarket
      x-amazon-apigateway-integration:
        type: MOCK
        requestTemplates:
          application/json: '{"statusCode": 201}'
        responses:
          default:
            statusCode: "201"
            responseTemplates:
              application/json: |
                {
                  "message": "Market created successfully",
                  "marketName": $input.json('$.market_name')
                }
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Market"
        required: true
      responses:
        "201":
          description: Market created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  marketName:
                    type: string
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not found
        "500":
          description: Internal server error

components:
  schemas:
    Market:
      type: object
      properties:
        market_name:
          type: string
          minLength: 1
      required:
        - market_name
      additionalProperties: false
